name: flutter_project_upgrader
description: "A CLI tool to upgrade old Flutter projects (Gradle, Kotlin, iOS Podfile, etc.)"
version: 0.0.4
homepage: https://github.com/Gourav-sharma/flutter_project_upgrader
repository: https://github.com/Gourav-sharma/flutter_project_upgrader
issue_tracker: https://github.com/Gourav-sharma/flutter_project_upgrader/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

executables:
  flutter_project_upgrader:

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# no plugin section needed, since this is Dart-only
